package com.example.dell.myapplication.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dell.myapplication.module.Msg;
import com.example.dell.myapplication.module.User;

import com.example.dell.myapplication.db.MsgDao;
import com.example.dell.myapplication.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgDaoConfig;
    private final DaoConfig userDaoConfig;

    private final MsgDao msgDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgDaoConfig = daoConfigMap.get(MsgDao.class).clone();
        msgDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        msgDao = new MsgDao(msgDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Msg.class, msgDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        msgDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public MsgDao getMsgDao() {
        return msgDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
